Update 01_BasicMicroservice.md
When I followed the instructions, I got the following error.

Z:\Code\Tanzu\nodejs_payment_calculator>npm start
•	nodejs-payment-calculator(*0.0.0 start
•	node ./bin/www
Z:\Code\Tanzu\nodejs_payment_calculator\app.js: 21 app.use(cors<));
A
ReferenceError: cors is not defined
at Object.<anonymous» (C:\Code\Tanzu\nodejs_payment_calculator\app.js:21:5)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node : internal/modules/cjs/loader : 1155:10)
at Module.load (node:internal/*odules/cjs/loader:981:32)
at Function.Module._load (node : internal/modules/cjs/loader : 822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous» (C:\Code\Tanzu\nodejs_payment_calculator\bin\www:7:11)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node : internal/modules/cjs/loader : 1155:10)

I found the solution at the Stackoverflow

https://stackoverflow.com/questions/7067966/why-doesnt-adding-cors-headers-to-an-options-route-allow-browsers-to-access-my

Adding the var cors = require('cors') before the app.use(cors()); fixed it and is runs!